version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_app_db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./finance-app-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=finance_app_db
      - JWT_SECRET=supersecretkey
      - CORS_ORIGIN=http://localhost:5173

  frontend:
    build: ./finance-app-ui
    ports:
      - "5173:5173"
    depends_on:
      - app
    environment:
      - VITE_API_BASE=http://localhost:8080
    volumes:
    - ./finance-app-ui:/app

volumes:
  db-data:
